### ISSUE TITLE
안녕하세요 ffmpeg 폴더는 어디에 넣나요?

### ISSUE THREAD

**Issue by dranoela** [Choonholic/ChzzkDownloader#2]
어떠한 설명도 없어서 질문드려봅니다

**Comment by dranoela** [comment]
혹은 제가 모르는 설치 방법이 있을까요? streamlink는 쓰던 게 있는데 미지원이라고 뜨는데 정상 작동 되는 걸까요?

**Comment by Choonholic** [comment]
혹시 사용 중이신 Streamlink 버전이 어떻게 되실까요?

Chzzk Live Downloader가 지원하는 버전은 공식적으로 6.7.3 이상이고, 그 이하의 버전이 설치되어 있을 경우에는 지원하지 않아 다운로드가 불가능합니다.

**Comment by Choonholic** [comment]
ffmpeg은 어디에 넣는 것이 아니라 how_to_install_ffmpeg.pdf 문서에 따라 ffmpeg을 설치하시거나, 또는 이미 ffmpeg이 설치되어 있다면 해당 디렉터리를 시스템 경로에 추가하시면 됩니다.

**Comment by dranoela** [comment]
ffmpeg 덕분에 인식 성공했습니다... 근데 스트림링크는 7.0 깔았는데도 인식이 안 되네요 6.72 이상 6.X버전을 깔아야할까요?

**Comment by Choonholic** [comment]
혹시 명령 프롬프트를 열어서 경로 변경 없이 아무 곳에서나 streamlink --version이라고 입력했을 때 버전이 표시되는지 확인해 보시기 바랍니다.

재부팅 후에 실행해도 표시가 안 된다면 ffmpeg과 마찬가지로 수동으로 경로를 추가하신 다음 확인해 보시고 결과를 알려주시겠어요?

**Comment by dranoela** [comment]
프로그램 추가제거 삭제, program files에 있는 스트림링크 파일 삭제, appdata roaming에 있는 streamlink 폴더 삭제 후 재부팅 및 7.0 312설치에도 6.7.2라고 뜹니다

**Comment by Choonholic** [comment]
그럼 Streamlink 6.7.2가 숨어 있을 뿐만 아니라 아마 이전에 사용하셨던 도구로 인해 시스템 설정이 완전히 꼬여 있다 보시면 됩니다. 그리고 Streamlink 안에도 Python 3.12 기능 축소판이 들어 있기 때문에 이 역시 영향을 미치고 있을 겁니다.

Streamlink 색출은 명령행 프롬프트에서 다음과 같이 할 수 있습니다.

cd \
dir streamlink.exe /s /w

결과에 Streamlink.exe가 있는 디렉터리를 확인하셔서 삭제하시고, PATH에서도 해당 디렉터리가 있으면 삭제해 주세요.

만약 D모 커뮤니티 S갤러리에서 배포 중인 도구를 사용하셨다면 해당 도구 디렉터리 안에 들어있을 겁니다. 해당 도구와는 상성이 좋지 않습니다.

**Comment by Choonholic** [comment]
Closed due to no additional information being provided within 48 hours.
