### ISSUE TITLE
스트리머별 폴더 자동 생성 기능

### ISSUE THREAD

**Issue by uaevuon** [Choonholic/ChzzkDownloader#3]
ChzzkVideoDownloader 사용 시 스트리머별 폴더 자동 생성되는걸 막고 싶은데 설정 방법이 없나요?

pdf나 --help 읽어봐도 비활성화하는 법이 없는 것 같아 issue에 질문 남깁니다.

**Comment by uaevuon** [comment]
그리고 혹시 파일명에 비디오 번호를 넣을 수 있는 방법이 있나요? 미리 정의된 태그는 없는 것 같은데 혹시 이것도 추후 업데이트에 추가 가능할까요?

**Comment by Choonholic** [comment]
라이브 스트리밍의 경우 비디오 번호 정보가 존재하지 않습니다. 비디오 번호는 다시 보기 비디오에만 부여되며, 클립에는 클립 UID가 부여됩니다.

**Comment by Choonholic** [comment]
버전 0.99에서 요청 사항이 적용되었습니다.

* **스트리머 분류 기능 끄기**
  * 다운로드 도구를 직접 실행하실 경우 `--category none` 선택 사항을 추가하시면 적용됩니다. 매번 적용할 필요없이 한 번 적용하면 설정 파일에 저장됩니다.
  * 다운로드 관리자를 사용하실 경우 디렉터리 설정에서 적용하실 수 있습니다.
  
* **파일명에 비디오 번호 넣기**
  * 새로 추가된 태그를 확인해 보시기 바랍니다.
  * 라이브 스트림 - `{channel_uid}`
  * 다시 보기 비디오 - `{video_no}`
  * 클립 - `{clip_uid}`

**Comment by uaevuon** [comment]
--category none을 추가하면 설정 파일에 output_categorize 항목이 0 값으로 생기고 폴더 생성 없이 받긴 하지만, 이후 사용시에 --category none 을 생략하면 output_categorize의 값이 1로 바뀌며 기존대로 폴더에 받습니다.

**Comment by Choonholic** [comment]
확인 감사합니다.

해당 부분은 검토 결과, 매개 변수 처리 부분에 버그가 있어 발생하는 문제로 해당 매개 변수 외에 다른 매개 변수에서도 저장된 값이 다음 실행 시 초기값으로 돌아가는 문제가 있는 것을 확인하였습니다.

해당 문제를 장기간 놓치고 있었던 부분에 대해 깊이 사과드리며, 긴급하게 버전 1.0으로 갱신하여 내일 중으로 배포하겠습니다.

매우 번거로우시겠지만, 배포 전까지만 `--category none` 매개 변수를 매번 지정 부탁드립니다.

덕분에 심각한 오류를 확인할 수 있었습니다.
다시 한 번 감사드립니다.

**Comment by Choonholic** [comment]
버전 1.00.00이 배포되었으니 확인 부탁드립니다.
감사합니다.
