### ISSUE TITLE
[기능 요청] --exist에 skip 기능 추가

### ISSUE THREAD

**Issue by uaevuon** [Choonholic/ChzzkDownloader#4]
현재 --exist에 기본값으로 rename 옵션과 overwrite 옵션만 있는데, 동일한 파일 발견시 아예 skip하는 옵션도 있으면 좋을 것 같습니다.

**Comment by Choonholic** [comment]
`Skip` 기능을 넣는 것은 어렵지 않으나, 라이브 스트림의 경우 한 번 다운로드를 놓치면 다시 받는 것이 불가능하기에 위험도가 높은 기능입니다.

먼저, 해당 기능은 내부적으로 해당 파일과 동일한 **이름**의 파일이 있는지의 여부만 판단합니다. 

그리고 같은 파일인지의 여부를 판단할 수 없는데, 파일의 내용을 판단하려면 어쨌든 다운로드를 하기는 해야 하고, 다운로드를 한 다음 비교해서 무시하고 넘어간다면 사실 상 `overwrite`와 완전히 동일한 결과를 가져옵니다. 저장 공간도 일단 똑같이 차지했다가 삭제되는 결과를 가져오고요.

따라서 `skip` 선택 사항을 추가하게 된다면, 파일의 실제 내용이 동일한가의 여부와 무관하게 동일한 **이름**의 파일이 있으면 넘어가게 구현될 것입니다.

물론 `--name` 옵션만 제대로 잘 지정하셨다면 저장되어야 하는 파일이 삭제되는 일은 일어나지 않을 것이기에, 어떤 용도로 쓰실지는 잘 모르겠지만, 일단 다음 버전에 추가하도록 요청해 두도록 하겠습니다.

항상 소중한 의견 감사드립니다.

**Comment by uaevuon** [comment]
네, 동일한 파일 이름이 발견되면 skip하는 방식을 생각한게 맞습니다.

txt 파일에 다시보기 주소와 함께 관련 메모를 적어두고 -i 옵션으로 다량의 다시보기 영상을 받고있는데, 이미 받은 영상 주소 라인 마다 주석 처리를 매번 하다가 skip 기능이 있으면 좋을거같아 생각났습니다.
다시보기를 받을 땐 파일명에 {video_no}을 넣어서 서로 다른 영상이 같은 파일명을 가질 일은 안 생기는데, 라이브 방송은 방제가 같으면 위험할 수 있겠네요.

감사합니다.

**Comment by Choonholic** [comment]
버전 1.1.0이 배포되었습니다.

감사합니다.
