### ISSUE TITLE
[버그] 일부 다시보기 영상을 받을 수 없는 문제

### ISSUE THREAD

**Issue by uaevuon** [Choonholic/ChzzkDownloader#5]
```
PS E:\새 폴더> ./ChzzkVideoDownloader 4476578
Chzzk Video Downloader, Version 1.0.0
Written by Choonholic. November 25, 2024 23:00:00

An error occurred while retrieving video status: 'NoneType' object has no attribute 'strip'
Video 4476578 is not valid or removed from Chzzk.
```

[위 영상](https://chzzk.naver.com/video/4476578) 뿐만 아니라 일부 영상들은 다시보기 영상 페이지가 그대로 남아있어도 위와 같은 오류를 내면서 받지 못하는 버그가 있습니다.
이런 영상들에 어떤 공통점이 있는지는 모르겠습니다.

**Comment by Choonholic** [comment]
해당 문제는 스트리머가 영상에 대한 카테고리 값이나 기타 필수 값을 입력하지 않은 경우 발생합니다.

1.1.0에서 해당 값이 제대로 설정되어 있지 않더라도 다운로드가 가능하도록 수정하였습니다.
항상 간결하면서도 정확한 버그 리포트 감사합니다.

**Comment by Choonholic** [comment]
버전 1.1.0이 배포되었습니다.

감사합니다.
