### ISSUE TITLE
[버그] 썸네일 다운로드시 파일명이 이미 존재하면 디버깅 문구 출력

### ISSUE THREAD

**Issue by uaevuon** [Choonholic/ChzzkDownloader#6]
사용에 영향주는 내용은 아닙니다

썸네일도 받게 설정해둔 상태에서 이미 받은 영상 파일이 존재할 때는 동일 파일 존재해서 아래와 같이 skip한다는 문구를 띄우는데,
The download has been skipped because a file with the same name as the target file already exists.

이전에 영상을 받다가 중단하여 영상은 없고 썸네일 이미지파일만 남아있을 경우 아래와 같은 문구가 나옵니다
An error occurred while downloading thumbnail image: expected str, bytes or os.PathLike object, not NoneType

**Comment by Choonholic** [comment]
훌륭한 버그 보고 항상 감사드립니다.

확인 결과 미리보기 파일에 대한 검증 루틴은 Live, Video, Clip 모두 처리하고 있으나,
처리 후 다운로드를 결정하는 부분에 있어서 Live에서만 이를 처리하고,
Video, Clip은 다운로드할 파일 정보가 없음에도 불구하고 다운로드를 시도하는 코드가 남아 있음을 확인하였습니다.

해당 버그는 내일 배포될 예정인 버전 1.3.0에 포함될 수 있도록 테스트 진행 중입니다.

감사합니다.

**Comment by Choonholic** [comment]
버전 1.3.0이 배포되었습니다.

감사합니다.
