### ISSUE TITLE
[버그?] 스트리머를 차단한 상태에선 다시보기 존재해도 Video not found. Please check and try again. 가 뜸

### ISSUE THREAD

**Issue by uaevuon** [Choonholic/ChzzkDownloader#8]
사실 이런 케이스가 많지는 않겠지만 어쩌다보니 발견했습니다.

스트리머를 사용자 차단해둔 상태에서는 다시보기 영상이 연령제한이 걸려있든 안 걸려있든 일단 저장된 auth를 가지고 접근하는지 다시보기 영상은 그대로 있음에도 Video nnnnnnn not found. Please check and try again. 라고 나오고 스킵됩니다.

**Comment by Choonholic** [comment]
기본적으로 API를 호출할 때 인증 정보를 적용하기 때문에, 사용자를 차단하면 해당 다시보기 비디오의 정보를 얻어오는 것이 불가능합니다.

사용자를 차단한 상태에서 성인 인증이 필요없는 비디오를 다운로드하고 싶다면 버전 1.5.1 이상에서 다음과 같은 옵션을 사용하시면 임시로 인증 정보를 무시하고 API를 호출하며, 다운로드가 정상적으로 진행됩니다.

```
ChzzkVideoDownloader <Video_URL_or_number> -a ignore
ChzzkVideoDownloader <Video_URL_or_number> --auth ignore
```

물론 성인 인증이 필요한 비디오인 경우, 인증하면서 차단이 적용되므로 다운로드하실 수 없습니다.

참고로 `-a` 또는 `--auth` 매개 변수는 본래 기존의 인증 정보를 재설정하는 기능을 가지고 있었으며, 해당 기능은 다음과 같이 호출하는 것으로 변경되었습니다.

```
ChzzkVideoDownloader <Video_URL_or_number> -a reset
ChzzkVideoDownloader <Video_URL_or_number> --auth reset
```

버전 1.5.1은 12월 25일 오후 18시에 배포되었습니다.
보고 감사드립니다.
